name: maas
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  quiver: ^2.0.1
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  datetime_picker_formfield: ^0.1.6

dev_dependencies:
  test: ^1.5.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: LohitNepali
      fonts:
        - asset: assets/LohitNepali/Lohit-Nepali.ttf
